---

- name: Install Apache2 on web1
  hosts: web1
  become: true

  tasks:
    - name: Install Apache2 package
      apt:
        name: Apache2
        state: present
        update_cache: yes

      - name: Ensure Apache2 service is running
        service: 
          name: apache2
          state: started
          enabled: yes